version: "3"
services:
  unite-cbmc:
    image: unite-cbmc
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9106:9106"
        - "9107:9107"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9106
        - UNITE_COMPILATION_PORT=9107
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost