// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury       - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Jim Amsden          - Support for UI Preview (494303)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package verifit.compilation.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import verifit.compilation.VeriFitCompilationManager;
import verifit.compilation.VeriFitCompilationConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import verifit.compilation.resources.FitDomainConstants;
import verifit.compilation.servlet.ServiceProviderCatalogSingleton;
import org.eclipse.lyo.oslc.domains.auto.AutomationPlan;
import org.eclipse.lyo.oslc.domains.auto.AutomationRequest;
import org.eclipse.lyo.oslc.domains.auto.AutomationResult;
import org.eclipse.lyo.oslc.domains.auto.ParameterDefinition;
import org.eclipse.lyo.oslc.domains.auto.ParameterInstance;
import org.eclipse.lyo.oslc.domains.Person;
import verifit.compilation.resources.SUT;
import verifit.compilation.resources.TextOut;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code
@OslcService(Oslc_autoDomainConstants.AUTOMATION_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/resources")
public class ServiceProviderService1
{
    @Context private HttpServletRequest httpServletRequest;
    @Context private HttpServletResponse httpServletResponse;
    @Context private UriInfo uriInfo;

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public ServiceProviderService1()
    {
        super();
    }

    @OslcQueryCapability
    (
        title = "QueryCapability1",
        label = "QueryCapability1",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + FitDomainConstants.SUT_PATH,
        resourceTypes = {FitDomainConstants.SUT_TYPE},
        usages = {}
    )
    @GET
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public SUT[] querySUTs(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code querySUTs
        // Here additional logic can be implemented that complements main action taken in VeriFitCompilationManager
        // End of user code

        final List<SUT> resources = VeriFitCompilationManager.querySUTs(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new SUT [resources.size()]);
    }

    @GET
    @Path("query")
    @Produces({ MediaType.TEXT_HTML })
    public Response querySUTsAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code querySUTsAsHtml
        // End of user code

        final List<SUT> resources = VeriFitCompilationManager.querySUTs(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code querySUTsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sutscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcQueryCapability
    (
        title = "QueryCapability2",
        label = "QueryCapability2",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONREQUEST_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
        usages = {}
    )
    @GET
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationRequest[] queryAutomationRequests(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationRequests
        // Here additional logic can be implemented that complements main action taken in VeriFitCompilationManager
        // End of user code

        final List<AutomationRequest> resources = VeriFitCompilationManager.queryAutomationRequests(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationRequest [resources.size()]);
    }

    @GET
    @Path("query")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationRequestsAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationRequestsAsHtml
        // End of user code

        final List<AutomationRequest> resources = VeriFitCompilationManager.queryAutomationRequests(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationRequestsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcQueryCapability
    (
        title = "QueryCapability3",
        label = "QueryCapability3",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONRESULT_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONRESULT_TYPE},
        usages = {}
    )
    @GET
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationResult[] queryAutomationResults(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationResults
        // Here additional logic can be implemented that complements main action taken in VeriFitCompilationManager
        // End of user code

        final List<AutomationResult> resources = VeriFitCompilationManager.queryAutomationResults(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationResult [resources.size()]);
    }

    @GET
    @Path("query")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationResultsAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationResultsAsHtml
        // End of user code

        final List<AutomationResult> resources = VeriFitCompilationManager.queryAutomationResults(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationResultsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresultscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcQueryCapability
    (
        title = "QueryCapability4",
        label = "QueryCapability4",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONPLAN_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
        usages = {}
    )
    @GET
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan[] queryAutomationPlans(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlans
        // Here additional logic can be implemented that complements main action taken in VeriFitCompilationManager
        // End of user code

        final List<AutomationPlan> resources = VeriFitCompilationManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationPlan [resources.size()]);
    }

    @GET
    @Path("query")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationPlansAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlansAsHtml
        // End of user code

        final List<AutomationPlan> resources = VeriFitCompilationManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationPlansAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplanscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcDialog
    (
         title = "SelectionDialog1",
         label = "SelectionDialog1",
         uri = "serviceProviders/{serviceProviderId}/resources/selector",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {FitDomainConstants.SUT_TYPE},
         usages = {}
    )
    @GET
    @Path("selector")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void SUTSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code SUTSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code SUTSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<SUT> resources = VeriFitCompilationManager.SUTSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sutselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sutselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    @OslcDialog
    (
         title = "SelectionDialog2",
         label = "SelectionDialog2",
         uri = "serviceProviders/{serviceProviderId}/resources/selector",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @GET
    @Path("selector")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationRequestSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationRequestSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationRequestSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationRequest> resources = VeriFitCompilationManager.AutomationRequestSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    @OslcDialog
    (
         title = "SelectionDialog3",
         label = "SelectionDialog3",
         uri = "serviceProviders/{serviceProviderId}/resources/selector",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONRESULT_TYPE},
         usages = {}
    )
    @GET
    @Path("selector")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationResultSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationResultSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationResultSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationResult> resources = VeriFitCompilationManager.AutomationResultSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresultselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresultselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    @OslcDialog
    (
         title = "SelectionDialog4",
         label = "SelectionDialog4",
         uri = "serviceProviders/{serviceProviderId}/resources/selector",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
         usages = {}
    )
    @GET
    @Path("selector")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationPlanSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationPlanSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationPlanSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationPlan> resources = VeriFitCompilationManager.AutomationPlanSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplanselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplanselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    /**
     * Create a single AutomationRequest via RDF/XML, XML or JSON POST
     *
     * @throws IOException
     * @throws ServletException
     */
    @OslcCreationFactory
    (
         title = "CreationFactory3",
         label = "CreationFactory3",
         resourceShapes = {OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONREQUEST_PATH},
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @POST
    @Path("create")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public Response createAutomationRequest(
            @PathParam("serviceProviderId") final String serviceProviderId ,
            final AutomationRequest aResource
        ) throws IOException, ServletException
    {
        try {
            AutomationRequest newResource = VeriFitCompilationManager.createAutomationRequest(httpServletRequest, aResource, serviceProviderId);
            httpServletResponse.setHeader("ETag", VeriFitCompilationManager.getETagFromAutomationRequest(newResource));
            return Response.created(newResource.getAbout()).entity(newResource).header(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2).build();
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }

    /**
     * OSLC delegated creation dialog for a single resource
     *
     * @throws IOException
     * @throws ServletException
     */
    @GET
    @Path("creator")
    @Consumes({MediaType.WILDCARD})
    public void AutomationRequestCreator(
                @PathParam("serviceProviderId") final String serviceProviderId
        ) throws IOException, ServletException
    {
        // Start of user code AutomationRequestCreator
        // End of user code

        httpServletRequest.setAttribute("creatorUri", UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
        httpServletRequest.setAttribute("serviceProviderId", serviceProviderId);

        RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestcreator.jsp");
        rd.forward(httpServletRequest, httpServletResponse);
    }

    /**
     * Backend creator for the OSLC delegated creation dialog.
     *
     * Accepts the input in FormParams and returns a small JSON response
     */
    @OslcDialog
    (
         title = "CreationDialog3",
         label = "CreationDialog3",
         uri = "serviceProviders/{serviceProviderId}/resources/creator",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @POST
    @Path("creator")
    @Consumes({ MediaType.APPLICATION_FORM_URLENCODED})
    public void createAutomationRequestFromDialog(
            @PathParam("serviceProviderId") final String serviceProviderId
        ) {
        try {
            AutomationRequest newResource = null;

            AutomationRequest aResource = new AutomationRequest();

            String[] paramValues;

            paramValues = httpServletRequest.getParameterValues("contributor");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addContributor(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("created");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setCreated(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("creator");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addCreator(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("description");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setDescription(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("identifier");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setIdentifier(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("modified");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setModified(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("type");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addType(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("title");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setTitle(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("instanceShape");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setInstanceShape(new URI(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("serviceProvider");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addServiceProvider(new URI(paramValues[i]));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("state");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addState(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("desiredState");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setDesiredState(new Link(new URI(paramValues[0])));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("inputParameter");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addInputParameter(new ParameterInstance(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("executesAutomationPlan");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setExecutesAutomationPlan(new Link(new URI(paramValues[0])));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }

            newResource = VeriFitCompilationManager.createAutomationRequestFromDialog(httpServletRequest, aResource, serviceProviderId);

            if (newResource != null) {
                httpServletRequest.setAttribute("newResource", newResource);
                httpServletRequest.setAttribute("newResourceUri", newResource.getAbout().toString());

                // Send back to the form a small JSON response
                httpServletResponse.setContentType("application/json");
                httpServletResponse.setStatus(Status.CREATED.getStatusCode());
                httpServletResponse.addHeader("Location", newResource.getAbout().toString());
                PrintWriter out = httpServletResponse.getWriter();

                JSONObject oslcResponse = new JSONObject();
                JSONObject newResourceJson = new JSONObject();
                newResourceJson.put("rdf:resource", newResource.getAbout().toString());
                // Start of user code OSLC Resource Label
                newResourceJson.put("oslc:label", newResource.toString());
                // End of user code
                oslcResponse.put("oslc:results", new Object[]{newResourceJson});

                out.print(oslcResponse.toString());
                out.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }
    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan getAutomationPlan(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitCompilationManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            // Start of user code getAutomationPlan
            // End of user code
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return aAutomationPlan;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationPlanAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtml_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitCompilationManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplan.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationPlanCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationPlanCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitCompilationManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationPlan.getAbout());
            compact.setTitle(aAutomationPlan.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlSmallPreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitCompilationManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplansmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlLargePreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitCompilationManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationplanlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("sUTs/{sUTId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public SUT getSUT(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("sUTId") final String sUTId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final SUT aSUT = VeriFitCompilationManager.getSUT(httpServletRequest, serviceProviderId, sUTId);

        if (aSUT != null) {
            // Start of user code getSUT
            // End of user code
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return aSUT;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("sUTs/{sUTId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getSUTAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("sUTId") final String sUTId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getSUTAsHtml_init
        // End of user code

        final SUT aSUT = VeriFitCompilationManager.getSUT(httpServletRequest, serviceProviderId, sUTId);

        if (aSUT != null) {
            httpServletRequest.setAttribute("aSUT", aSUT);
            // Start of user code getSUTAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sut.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("sUTs/{sUTId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getSUTCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("sUTId") final String sUTId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getSUTCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final SUT aSUT = VeriFitCompilationManager.getSUT(httpServletRequest, serviceProviderId, sUTId);

        if (aSUT != null) {
            final Compact compact = new Compact();

            compact.setAbout(aSUT.getAbout());
            compact.setTitle(aSUT.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aSUT.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aSUT.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("sUTs/{sUTId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getSUTAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("sUTId") final String sUTId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getSUTAsHtmlSmallPreview_init
        // End of user code

        final SUT aSUT = VeriFitCompilationManager.getSUT(httpServletRequest, serviceProviderId, sUTId);

        if (aSUT != null) {
            httpServletRequest.setAttribute("aSUT", aSUT);
            // Start of user code getSUTAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sutsmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("sUTs/{sUTId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getSUTAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("sUTId") final String sUTId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getSUTAsHtmlLargePreview_init
        // End of user code

        final SUT aSUT = VeriFitCompilationManager.getSUT(httpServletRequest, serviceProviderId, sUTId);

        if (aSUT != null) {
            httpServletRequest.setAttribute("aSUT", aSUT);
            // Start of user code getSUTAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/sutlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationRequest getAutomationRequest(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitCompilationManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            // Start of user code getAutomationRequest
            // End of user code
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return aAutomationRequest;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationRequestAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtml_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitCompilationManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequest.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationRequestCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationRequestCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitCompilationManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationRequest.getAbout());
            compact.setTitle(aAutomationRequest.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlSmallPreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitCompilationManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestsmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlLargePreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitCompilationManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationrequestlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationResult getAutomationResult(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitCompilationManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            // Start of user code getAutomationResult
            // End of user code
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return aAutomationResult;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationResultAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtml_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitCompilationManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresult.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationResultCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationResultCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationResult aAutomationResult = VeriFitCompilationManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationResult.getAbout());
            compact.setTitle(aAutomationResult.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlSmallPreview_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitCompilationManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresultsmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlLargePreview_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitCompilationManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/compilation/automationresultlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitCompilationConstants.HDR_OSLC_VERSION, VeriFitCompilationConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
}
