# how to in local docker:
#   run the image:
#     $ docker run -it --entrypoint /bin/bash maven:3.6.3-jdk-8
#
#   install newman:
#     $ apt-get update && apt-get install -y nodejs npm && npm install -g newman
#
#   clone repository
#     $ git clone https://pajda.fit.vutbr.cz/verifit/oslc-generic-analysis.git
#   
#   ...

image: maven:3.6.3-jdk-8

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .m2/repository

stages:
  - build
  - test

build:
  stage: build
  script:
    - /bin/bash ./build.sh
    - du -sh analysis/target compilation/target shared/target domain/target
  artifacts: # TODO artifacts were too big...
    paths:
    - analysis/target
    - compilation/target
    - shared/target
    - domain/target
    - analysis/VeriFitAnalysis.properties
    - compilation/VeriFitCompilation.properties
    - sparql_triplestore/jetty-distribution/start.ini
    expire_in: 20 minutes

# test that Unite can start
test-start:
  stage: test
  script: /bin/bash ./dev_tools/ci_test_start.sh

# test the main functionality of Unite
test-newman-core:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm install -g newman
  script: /bin/bash ./dev_tools/ci_test_suite.sh

# test keepLastN functionality
test-newman-keepLastN:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm install -g newman
  script: /bin/bash ./dev_tools/ci_test_keep_last_n.sh

# test port configuration through environment variables
test-newman-env-ports:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm install -g newman
  script: /bin/bash ./dev_tools/ci_test_environments_ports.sh
