version: "3"
services:
  unite-anaconda:
    build: .
    ports:
        - "8080:8080" # CHANGE PORTS HERE IF NEEDED
        - "8081:8081" # and here
    environment:
        - UNITE_ANALYSIS_PORT=8080    # and here
        - UNITE_COMPILATION_PORT=8081 # and here