version: "3"
services:
  unite-anaconda:
    image: unite-anaconda
    build: .
    
    restart: unless-stopped

    # needed by anaconda (/proc/sys/kernel/yama/ptrace_scope)
    privileged: true

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9096:9096"
        - "9097:9097"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9096
        - UNITE_COMPILATION_PORT=9097
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost