// Start of user code Copyright
/* ## License for manual implementation (enclosed in "Start/End user code ..." tags) ##
 *
 * Copyright (C) 2020 Ondřej Vašíček <ondrej.vasicek.0@gmail.com>, <xvasic25@stud.fit.vutbr.cz>
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/* ## License for generated code: ## */
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains.auto;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_autoDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String AUTOMATION_DOMAIN = "http://open-services.net/ns/auto#";
    public static String AUTOMATION_NAMSPACE = "http://open-services.net/ns/auto#";
    public static String AUTOMATION_NAMSPACE_PREFIX = "oslc_auto";

    public static String AUTOMATIONPLAN_PATH = "automationPlan";
    public static String AUTOMATIONPLAN_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONPLAN_LOCALNAME = "AutomationPlan"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONPLAN_TYPE = AUTOMATIONPLAN_NAMESPACE + AUTOMATIONPLAN_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_PATH = "automationRequest";
    public static String AUTOMATIONREQUEST_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_LOCALNAME = "AutomationRequest"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_TYPE = AUTOMATIONREQUEST_NAMESPACE + AUTOMATIONREQUEST_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_PATH = "automationResult";
    public static String AUTOMATIONRESULT_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_LOCALNAME = "AutomationResult"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_TYPE = AUTOMATIONRESULT_NAMESPACE + AUTOMATIONRESULT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String CONTRIBUTION_PATH = "contribution";
    public static String CONTRIBUTION_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String CONTRIBUTION_LOCALNAME = "Contribution"; //localName of the rdfs:class the resource describes
    public static String CONTRIBUTION_TYPE = CONTRIBUTION_NAMESPACE + CONTRIBUTION_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PARAMETERDEFINITION_PATH = "parameterDefinition";
    public static String PARAMETERDEFINITION_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PARAMETERDEFINITION_LOCALNAME = "ParameterDefinition"; //localName of the rdfs:class the resource describes
    public static String PARAMETERDEFINITION_TYPE = PARAMETERDEFINITION_NAMESPACE + PARAMETERDEFINITION_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_PATH = "parameterInstance";
    public static String PARAMETERINSTANCE_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_LOCALNAME = "ParameterInstance"; //localName of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_TYPE = PARAMETERINSTANCE_NAMESPACE + PARAMETERINSTANCE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
