FROM unite:latest

# copy over Unite configuration for Theta
COPY ./unite-conf/* ./unite/conf/analysis_advanced/AnalysisTools/

# install Theta
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    git clone --depth 1 --branch v4.0.0 https://github.com/ftsrg/theta.git; cd theta && \
    ./gradlew clean && \
    ./gradlew theta-xsts-cli:build && \
    mv subprojects/xsts/xsts-cli/build/libs/theta-xsts-cli-*-all.jar ./theta-xsts-cli.jar && \
    ./gradlew theta-xcfa-cli:build && \
    mv subprojects/xcfa/xcfa-cli/build/libs/theta-xcfa-cli-*-all.jar ./theta-xcfa-cli.jar && \
    cd ../

# z3 libraries need to be in path
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/theta/lib/"
