version: "3"
services:
  unite-theta:
    image: unite-theta
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9092:9092"
        - "9093:9093"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9092
        - UNITE_COMPILATION_PORT=9093
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost