// Start of user code Copyright

/* ## License for manual implementation (enclosed in "// Start of user code ..." and "// End of user code ...") and some modifications ##
 *
 * Copyright (C) 2020 Ondřej Vašíček <ondrej.vasicek.0@gmail.com>, <xvasic25@stud.fit.vutbr.cz>
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// ## License for generated code: ##
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury       - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Jim Amsden          - Support for UI Preview (494303)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package verifit.analysis.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import verifit.analysis.VeriFitAnalysisManager;
import verifit.analysis.VeriFitAnalysisConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import verifit.analysis.servlet.ServiceProviderCatalogSingleton;
import org.eclipse.lyo.oslc.domains.auto.AutomationPlan;
import org.eclipse.lyo.oslc.domains.auto.AutomationRequest;
import org.eclipse.lyo.oslc.domains.auto.AutomationResult;
import org.eclipse.lyo.oslc.domains.auto.Contribution;
import org.eclipse.lyo.oslc.domains.auto.ParameterDefinition;
import org.eclipse.lyo.oslc.domains.auto.ParameterInstance;
import org.eclipse.lyo.oslc.domains.Person;
import verifit.analysis.resources.SUT;

// Start of user code imports
import verifit.analysis.exceptions.OslcResourceException;
import org.eclipse.lyo.oslc4j.core.model.Error;
import java.io.File;
// End of user code

// Start of user code pre_class_code
// End of user code
@OslcService(Oslc_autoDomainConstants.AUTOMATION_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/resources")
public class ServiceProviderService1
{
    @Context private HttpServletRequest httpServletRequest;
    @Context private HttpServletResponse httpServletResponse;
    @Context private UriInfo uriInfo;

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    @GET
    @Path("contributions/{contributionId}")
    @Produces({MediaType.APPLICATION_OCTET_STREAM})
    public Response getContribution(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("contributionId") final String contributionId
        ) throws IOException, ServletException, URISyntaxException
    {
        final File aContribution = VeriFitAnalysisManager.getContribution(httpServletRequest, serviceProviderId, contributionId);

        return Response.ok(aContribution, MediaType.APPLICATION_OCTET_STREAM)
        	      .header("Content-Disposition", "attachment; filename=\"" + aContribution.getName() + "\"" )
        	      .build();
    }

    @PUT
    @Path("contributions/{contributionId}")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public Response updateContribution(
            @HeaderParam("If-Match") final String eTagHeader,
            @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("contributionId") final String contributionId ,
            final Contribution aResource
        ) throws IOException, ServletException
    {
            try {
                final Contribution updatedResource = VeriFitAnalysisManager.updateContribution(httpServletRequest, aResource, serviceProviderId, contributionId);
                return Response.ok().header(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2).build();
            } catch (OslcResourceException e) {
                Error errorResource = new Error();
                errorResource.setStatusCode("400");
                errorResource.setMessage(e.getMessage());
                return Response.status(400).entity(errorResource).build();
            } catch (Exception e) {
                e.printStackTrace();
                throw new WebApplicationException(e);
            }

    }
    // End of user code

    public ServiceProviderService1()
    {
        super();
    }

    @OslcQueryCapability
    (
        title = "QueryAutoPlan",
        label = "QueryAutoPlan",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONPLAN_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
        usages = {}
    )
    @GET
    @Path("queryAutoPlan")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan[] queryAutomationPlans(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlans
        // Here additional logic can be implemented that complements main action taken in VeriFitAnalysisManager
        // End of user code

        final List<AutomationPlan> resources = VeriFitAnalysisManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationPlan [resources.size()]);
    }

    @GET
    @Path("queryAutoPlan")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationPlansAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlansAsHtml
        // End of user code

        final List<AutomationPlan> resources = VeriFitAnalysisManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationPlansAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplanscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcQueryCapability
    (
        title = "QueryAutoRequest",
        label = "QueryAutoRequest",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONREQUEST_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
        usages = {}
    )
    @GET
    @Path("queryAutoRequest")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationRequest[] queryAutomationRequests(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationRequests
        // Here additional logic can be implemented that complements main action taken in VeriFitAnalysisManager
        // End of user code

        final List<AutomationRequest> resources = VeriFitAnalysisManager.queryAutomationRequests(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationRequest [resources.size()]);
    }

    @GET
    @Path("queryAutoRequest")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationRequestsAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationRequestsAsHtml
        // End of user code

        final List<AutomationRequest> resources = VeriFitAnalysisManager.queryAutomationRequests(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationRequestsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcQueryCapability
    (
        title = "QueryAutoResult",
        label = "QueryAutoResult",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONRESULT_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONRESULT_TYPE},
        usages = {}
    )
    @GET
    @Path("queryAutoResult")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationResult[] queryAutomationResults(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationResults
        // Here additional logic can be implemented that complements main action taken in VeriFitAnalysisManager
        // End of user code

        final List<AutomationResult> resources = VeriFitAnalysisManager.queryAutomationResults(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationResult [resources.size()]);
    }

    @GET
    @Path("queryAutoResult")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationResultsAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationResultsAsHtml
        // End of user code

        final List<AutomationResult> resources = VeriFitAnalysisManager.queryAutomationResults(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationResultsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresultscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @OslcDialog
    (
         title = "SelectAutoPlan",
         label = "SelectAutoPlan",
         uri = "serviceProviders/{serviceProviderId}/resources/selectAutoPlan",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
         usages = {}
    )
    @GET
    @Path("selectAutoPlan")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationPlanSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationPlanSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationPlanSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationPlan> resources = VeriFitAnalysisManager.AutomationPlanSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplanselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplanselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    @OslcDialog
    (
         title = "SelectAutoRequest",
         label = "SelectAutoRequest",
         uri = "serviceProviders/{serviceProviderId}/resources/selectAutoRequest",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @GET
    @Path("selectAutoRequest")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationRequestSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationRequestSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationRequestSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationRequest> resources = VeriFitAnalysisManager.AutomationRequestSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    @OslcDialog
    (
         title = "SelectAutoResult",
         label = "SelectAutoResult",
         uri = "serviceProviders/{serviceProviderId}/resources/selectAutoResult",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONRESULT_TYPE},
         usages = {}
    )
    @GET
    @Path("selectAutoResult")
    @Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
    public void AutomationResultSelector(
        @QueryParam("terms") final String terms
        , @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
    {
        try {
            // Start of user code AutomationResultSelector_init
            // End of user code

            httpServletRequest.setAttribute("selectionUri",UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
            // Start of user code AutomationResultSelector_setAttributes
            // End of user code

            if (terms != null ) {
                httpServletRequest.setAttribute("terms", terms);
                final List<AutomationResult> resources = VeriFitAnalysisManager.AutomationResultSelector(httpServletRequest, serviceProviderId, terms);
                if (resources!= null) {
                            httpServletRequest.setAttribute("resources", resources);
                            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresultselectorresults.jsp");
                            rd.forward(httpServletRequest, httpServletResponse);
                }
                //a empty search should return an empty list and not NULL!
                throw new WebApplicationException(Status.NOT_FOUND);

            } else {
                try {
                    RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresultselector.jsp");
                    rd.forward(httpServletRequest, httpServletResponse);
                } catch (Exception e) {
                    throw new ServletException(e);
                }
            }
        } catch (Exception e) {
            throw new WebApplicationException(e);
        }
    }

    /**
     * Create a single AutomationRequest via RDF/XML, XML or JSON POST
     *
     * @throws IOException
     * @throws ServletException
     */
    @OslcCreationFactory
    (
         title = "CreateAutoRequest",
         label = "CreateAutoRequest",
         resourceShapes = {OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONREQUEST_PATH},
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @POST
    @Path("createAutoRequest")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public Response createAutomationRequest(
            @PathParam("serviceProviderId") final String serviceProviderId ,
            final AutomationRequest aResource
        ) throws IOException, ServletException
    {
        try {
            AutomationRequest newResource = VeriFitAnalysisManager.createAutomationRequest(httpServletRequest, aResource, serviceProviderId);
            httpServletResponse.setHeader("ETag", VeriFitAnalysisManager.getETagFromAutomationRequest(newResource));
            return Response.created(newResource.getAbout()).entity(newResource).header(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2).build();
        } catch (OslcResourceException e) {
               Error errorResource = new Error();
               errorResource.setStatusCode("400");
               errorResource.setMessage(e.getMessage());
               return Response.status(400).entity(errorResource).build();
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }

    /**
     * OSLC delegated creation dialog for a single resource
     *
     * @throws IOException
     * @throws ServletException
     */
    @GET
    @Path("creatorAutoRequest")
    @Consumes({MediaType.WILDCARD})
    public void AutomationRequestCreator(
                @PathParam("serviceProviderId") final String serviceProviderId
        ) throws IOException, ServletException
    {
        // Start of user code AutomationRequestCreator
        // End of user code

        httpServletRequest.setAttribute("creatorUri", UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(uriInfo.getPath()).build().toString());
        httpServletRequest.setAttribute("serviceProviderId", serviceProviderId);

        RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestcreator.jsp");
        rd.forward(httpServletRequest, httpServletResponse);
    }

    /**
     * Backend creator for the OSLC delegated creation dialog.
     *
     * Accepts the input in FormParams and returns a small JSON response
     */
    @OslcDialog
    (
         title = "CreatorAutoRequest",
         label = "CreatorAutoRequest",
         uri = "serviceProviders/{serviceProviderId}/resources/creatorAutoRequest",
         hintWidth = "0px",
         hintHeight = "0px",
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @POST
    @Path("creatorAutoRequest")
    @Consumes({ MediaType.APPLICATION_FORM_URLENCODED})
    public void createAutomationRequestFromDialog(
            @PathParam("serviceProviderId") final String serviceProviderId
        ) {
        try {
            AutomationRequest newResource = null;

            AutomationRequest aResource = new AutomationRequest();

            String[] paramValues;

            paramValues = httpServletRequest.getParameterValues("contributor");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addContributor(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("created");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setCreated(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("creator");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addCreator(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("description");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setDescription(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("identifier");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setIdentifier(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("modified");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setModified(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("type");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addType(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("title");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setTitle(paramValues[0]);
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("instanceShape");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setInstanceShape(new URI(paramValues[0]));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("serviceProvider");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addServiceProvider(new URI(paramValues[i]));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("state");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addState(new Link(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("desiredState");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setDesiredState(new Link(new URI(paramValues[0])));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("inputParameter");
            if (paramValues != null) {
                    for(int i=0; i<paramValues.length; i++) {
                        aResource.addInputParameter(new ParameterInstance(new URI(paramValues[i])));
                    }
            }
            paramValues = httpServletRequest.getParameterValues("executesAutomationPlan");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setExecutesAutomationPlan(new Link(new URI(paramValues[0])));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }
            paramValues = httpServletRequest.getParameterValues("producedAutomationResult");
            if (paramValues != null) {
                    if (paramValues.length == 1) {
                        if (paramValues[0].length() != 0)
                            aResource.setProducedAutomationResult(new Link(new URI(paramValues[0])));
                        // else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
                    }

            }

            newResource = VeriFitAnalysisManager.createAutomationRequestFromDialog(httpServletRequest, aResource, serviceProviderId);

            if (newResource != null) {
                httpServletRequest.setAttribute("newResource", newResource);
                httpServletRequest.setAttribute("newResourceUri", newResource.getAbout().toString());

                // Send back to the form a small JSON response
                httpServletResponse.setContentType("application/json");
                httpServletResponse.setStatus(Status.CREATED.getStatusCode());
                httpServletResponse.addHeader("Location", newResource.getAbout().toString());
                PrintWriter out = httpServletResponse.getWriter();

                JSONObject oslcResponse = new JSONObject();
                JSONObject newResourceJson = new JSONObject();
                newResourceJson.put("rdf:resource", newResource.getAbout().toString());
                // Start of user code OSLC Resource Label
                newResourceJson.put("oslc:label", newResource.toString());
                // End of user code
                oslcResponse.put("oslc:results", new Object[]{newResourceJson});

                out.print(oslcResponse.toString());
                out.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }
    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan getAutomationPlan(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitAnalysisManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            // Start of user code getAutomationPlan
            // End of user code
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return aAutomationPlan;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationPlanAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtml_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitAnalysisManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplan.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationPlanCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationPlanCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitAnalysisManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationPlan.getAbout());
            compact.setTitle(aAutomationPlan.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlSmallPreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitAnalysisManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplansmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlLargePreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = VeriFitAnalysisManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationplanlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationRequest getAutomationRequest(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitAnalysisManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            // Start of user code getAutomationRequest
            // End of user code
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return aAutomationRequest;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationRequestAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtml_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitAnalysisManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequest.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationRequestCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationRequestCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitAnalysisManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationRequest.getAbout());
            compact.setTitle(aAutomationRequest.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlSmallPreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitAnalysisManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestsmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlLargePreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = VeriFitAnalysisManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationrequestlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationResult getAutomationResult(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitAnalysisManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            // Start of user code getAutomationResult
            // End of user code
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return aAutomationResult;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationResultAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtml_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitAnalysisManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresult.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationResultCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationResultCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationResult aAutomationResult = VeriFitAnalysisManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationResult.getAbout());
            compact.setTitle(aAutomationResult.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlSmallPreview_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitAnalysisManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresultsmallpreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlLargePreview_init
        // End of user code

        final AutomationResult aAutomationResult = VeriFitAnalysisManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/verifit/analysis/automationresultlargepreview.jsp");
            httpServletResponse.addHeader(VeriFitAnalysisConstants.HDR_OSLC_VERSION, VeriFitAnalysisConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
}
