version: "3"
services:
  unite-valgrind:
    image: unite-valgrind
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9094:9094"
        - "9095:9095"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9094
        - UNITE_COMPILATION_PORT=9095
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost