version: "3"
services:
  unite-frama-c:
    image: unite-frama-c
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9098:9098"
        - "9099:9099"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9098
        - UNITE_COMPILATION_PORT=9099
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost