version: "3"
services:
  unite-infer:
    image: unite-infer
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9090:9090"
        - "9091:9091"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9090
        - UNITE_COMPILATION_PORT=9091
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost