version: "3"
services:
  unite-grep:
    image: grep
    build: .
    
    restart: unless-stopped

    # map ports based on your configuration (from conf. files or env variables here)
    # currently the outside and inside HOST&PORT has to be the same!
    ports:
        - "9102:9102"
        - "9103:9103"

    # env variables can be used to overrride conf. files
    environment:
        - UNITE_ANALYSIS_PORT=9102
        - UNITE_COMPILATION_PORT=9103
        - UNITE_ANALYSIS_HOST=http://localhost
        - UNITE_COMPILATION_HOST=http://localhost